
package frames;

import java.awt.Font;
import utils.Fonts;
import utils.Sounds;

/**
 *
 * @author Usuario
 */
public class ControlesPanel extends javax.swing.JPanel {

    /**
     * Creates new form SelectPlayers
     */
    FrmMenu frmMenu;
    public ControlesPanel(FrmMenu frmMenu) {
        initComponents();
        this.frmMenu = frmMenu;
        
        lblJ1Izquierda.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        lblJ1Arriba.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        lblJ1Derecha.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        lblJ1IAbajo.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        
        
        lblJ2Izquierda.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        lblJ2Arriba.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        lblJ2Derecha.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        lblJ2Abajo.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        
        
        lblJ3Izquierda.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        lblJ3Arriba.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        lblJ3Derecha.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        lblJ3Abajo.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        
        
        lblJ4Izquierda.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        lblJ4Arriba.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        lblJ4Derecha.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
        lblJ4Abajo.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,24f));
    
        btnAtras.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,48f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblJ1Arriba = new javax.swing.JLabel();
        lblJ1Izquierda = new javax.swing.JLabel();
        lblJ1Derecha = new javax.swing.JLabel();
        lblJ1IAbajo = new javax.swing.JLabel();
        lblJ2Derecha = new javax.swing.JLabel();
        lblJ2Izquierda = new javax.swing.JLabel();
        lblJ2Abajo = new javax.swing.JLabel();
        lblJ2Arriba = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblJ3Arriba = new javax.swing.JLabel();
        lblJ3Abajo = new javax.swing.JLabel();
        lblJ3Izquierda = new javax.swing.JLabel();
        lblJ3Derecha = new javax.swing.JLabel();
        lblJ4Derecha = new javax.swing.JLabel();
        lblJ4Izquierda = new javax.swing.JLabel();
        lblJ4Abajo = new javax.swing.JLabel();
        lblJ4Arriba = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(62, 66, 71));

        btnAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnAtras.setForeground(new java.awt.Color(222, 167, 22));
        btnAtras.setText("Atras");
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setFocusPainted(false);
        btnAtras.setFocusable(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sprites/entities/mario/mario_down02.png"))); // NOI18N

        lblJ1Arriba.setForeground(new java.awt.Color(255, 255, 255));
        lblJ1Arriba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ1Arriba.setText("W");

        lblJ1Izquierda.setForeground(new java.awt.Color(255, 255, 255));
        lblJ1Izquierda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ1Izquierda.setText("A");

        lblJ1Derecha.setForeground(new java.awt.Color(255, 255, 255));
        lblJ1Derecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ1Derecha.setText("D");

        lblJ1IAbajo.setForeground(new java.awt.Color(255, 255, 255));
        lblJ1IAbajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ1IAbajo.setText("S");

        lblJ2Derecha.setForeground(new java.awt.Color(255, 255, 255));
        lblJ2Derecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ2Derecha.setText("DERECHA");

        lblJ2Izquierda.setForeground(new java.awt.Color(255, 255, 255));
        lblJ2Izquierda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ2Izquierda.setText("ABAJO");

        lblJ2Abajo.setForeground(new java.awt.Color(255, 255, 255));
        lblJ2Abajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ2Abajo.setText("IZQUIERDA");

        lblJ2Arriba.setForeground(new java.awt.Color(255, 255, 255));
        lblJ2Arriba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ2Arriba.setText("ARRIBA");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sprites/entities/peach/peach_down02.png"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sprites/entities/mallow/mallow_down01.png"))); // NOI18N

        lblJ3Arriba.setForeground(new java.awt.Color(255, 255, 255));
        lblJ3Arriba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ3Arriba.setText("I");

        lblJ3Abajo.setForeground(new java.awt.Color(255, 255, 255));
        lblJ3Abajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ3Abajo.setText("J");

        lblJ3Izquierda.setForeground(new java.awt.Color(255, 255, 255));
        lblJ3Izquierda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ3Izquierda.setText("K");

        lblJ3Derecha.setForeground(new java.awt.Color(255, 255, 255));
        lblJ3Derecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ3Derecha.setText("L");

        lblJ4Derecha.setForeground(new java.awt.Color(255, 255, 255));
        lblJ4Derecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ4Derecha.setText("NUM_6");

        lblJ4Izquierda.setForeground(new java.awt.Color(255, 255, 255));
        lblJ4Izquierda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ4Izquierda.setText("NUM_5");

        lblJ4Abajo.setForeground(new java.awt.Color(255, 255, 255));
        lblJ4Abajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ4Abajo.setText("NUM_4");

        lblJ4Arriba.setForeground(new java.awt.Color(255, 255, 255));
        lblJ4Arriba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ4Arriba.setText("NUM_8");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sprites/entities/geno/geno_down02.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJ3Arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblJ3Abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJ3Izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJ3Derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJ2Arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblJ2Abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJ2Izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJ2Derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJ1Arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblJ1Izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJ1IAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJ1Derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJ4Arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblJ4Abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblJ4Izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblJ4Derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblJ1Arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblJ1Izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblJ1IAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblJ1Derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblJ2Arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblJ2Abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblJ2Izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblJ2Derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblJ3Arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblJ3Abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblJ3Izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblJ3Derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblJ4Arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblJ4Abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblJ4Izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblJ4Derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Sounds.reproduceOnce(Sounds.RETURN_SOUND);
        frmMenu.changePanel(0);
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblJ1Arriba;
    private javax.swing.JLabel lblJ1Derecha;
    private javax.swing.JLabel lblJ1IAbajo;
    private javax.swing.JLabel lblJ1Izquierda;
    private javax.swing.JLabel lblJ2Abajo;
    private javax.swing.JLabel lblJ2Arriba;
    private javax.swing.JLabel lblJ2Derecha;
    private javax.swing.JLabel lblJ2Izquierda;
    private javax.swing.JLabel lblJ3Abajo;
    private javax.swing.JLabel lblJ3Arriba;
    private javax.swing.JLabel lblJ3Derecha;
    private javax.swing.JLabel lblJ3Izquierda;
    private javax.swing.JLabel lblJ4Abajo;
    private javax.swing.JLabel lblJ4Arriba;
    private javax.swing.JLabel lblJ4Derecha;
    private javax.swing.JLabel lblJ4Izquierda;
    // End of variables declaration//GEN-END:variables
}
