/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames;

import java.awt.Font;
import utils.Fonts;
import utils.Sounds;

/**
 *
 * @author Usuario
 */
public class SelectPlayersPanel extends javax.swing.JPanel {

    /**
     * Creates new form SelectPlayers
     */
    FrmMenu frmMenu;
    public SelectPlayersPanel(FrmMenu frmMenu) {
        initComponents();
        this.frmMenu = frmMenu;
        
        btn2Players.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,28f));
        btn3Players.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,28f));
        btn4Players.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,28f));
        
        btnAtras.setFont(Fonts.NEW_SUPER_MARIO_FONT.deriveFont(Font.PLAIN,48f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        btn4Players = new javax.swing.JButton();
        btn2Players = new javax.swing.JButton();
        btn3Players = new javax.swing.JButton();

        setBackground(new java.awt.Color(62, 66, 71));

        btnAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnAtras.setForeground(new java.awt.Color(222, 167, 22));
        btnAtras.setText("Atras");
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setFocusPainted(false);
        btnAtras.setFocusable(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btn4Players.setBackground(new java.awt.Color(255, 255, 255));
        btn4Players.setForeground(new java.awt.Color(166, 14, 24));
        btn4Players.setText("4 Jugadores");
        btn4Players.setBorder(null);
        btn4Players.setBorderPainted(false);
        btn4Players.setFocusPainted(false);
        btn4Players.setFocusable(false);
        btn4Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4PlayersActionPerformed(evt);
            }
        });

        btn2Players.setBackground(new java.awt.Color(255, 255, 255));
        btn2Players.setForeground(new java.awt.Color(166, 14, 24));
        btn2Players.setText("2 Jugadores");
        btn2Players.setBorder(null);
        btn2Players.setBorderPainted(false);
        btn2Players.setFocusPainted(false);
        btn2Players.setFocusable(false);
        btn2Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2PlayersActionPerformed(evt);
            }
        });

        btn3Players.setBackground(new java.awt.Color(255, 255, 255));
        btn3Players.setForeground(new java.awt.Color(166, 14, 24));
        btn3Players.setText("3 Jugadores");
        btn3Players.setBorder(null);
        btn3Players.setBorderPainted(false);
        btn3Players.setFocusPainted(false);
        btn3Players.setFocusable(false);
        btn3Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3PlayersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btn2Players, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn3Players, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn4Players, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2Players, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3Players, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4Players, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn2PlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2PlayersActionPerformed
        Sounds.reproduceOnce(Sounds.LETSGO_MARIO_SOUND);
        Sounds.reproduceOnce(Sounds.START_GAME_SOUND);
        frmMenu.StopMusic();
        frmMenu.startGame(2);
    }//GEN-LAST:event_btn2PlayersActionPerformed

    private void btn4PlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4PlayersActionPerformed
        Sounds.reproduceOnce(Sounds.LETSGO_MARIO_SOUND);
        Sounds.reproduceOnce(Sounds.START_GAME_SOUND);
        frmMenu.StopMusic();
        frmMenu.startGame(4);
    }//GEN-LAST:event_btn4PlayersActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Sounds.reproduceOnce(Sounds.RETURN_SOUND);
        frmMenu.changePanel(0);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btn3PlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3PlayersActionPerformed
        Sounds.reproduceOnce(Sounds.LETSGO_MARIO_SOUND);
        Sounds.reproduceOnce(Sounds.START_GAME_SOUND);
        frmMenu.StopMusic();
        frmMenu.startGame(3);
    }//GEN-LAST:event_btn3PlayersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2Players;
    private javax.swing.JButton btn3Players;
    private javax.swing.JButton btn4Players;
    private javax.swing.JButton btnAtras;
    // End of variables declaration//GEN-END:variables
}
